title: Portfolio - Krishanth Murali
profile_img: assets/img/file (2).png
icon_img: assets/img/avatar.png

name: "Krishanth Murali"
job: "〈Student〉"

# phone_number: +49 176 73935888
address: Freiburg im Breisgau, Germany
email: krishanthmurali1@gmail.com
linkedin_username: krishanth-m
github_username: KrishanthMenon
# instagram_username: krishant_m_menon
# twitter_username: twitter
# facebook_username: facebook
# youtube_username: finiteinfinite7238
blog_url: https://x-finite.blogspot.com/

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag