title: Portfolio - Krishanth Murali
profile_img: assets/img/profile.webp
icon_img: assets/img/icon.webp

name: "Krishanth Murali"
job: "〈Student〉"

phone_number: +49 176 73935888
address: Freiburg im Breisgau, Germany
email: krishanthmurali1@gmail.com
linkedin_username: krishanth-m
github_username: github
instagram_username: krishant_m_menon
twitter_username: twitter
facebook_username: facebook
youtube_username: youtube
blog_url: homepage-url

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag